# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf
source = ~/.config/hypr/conf/environments.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/workspaces.conf

xwayland {
  enabled = true
  force_zero_scaling = true
}

ecosystem {
  no_update_news = true
}
