env = XCURSOR_THEME,breeze_cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GTK_THEME,Breeze-Dark

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,kde
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_FONT_DPI,96
env = XDG_MENU_PREFIX,plasma-

#kime
env = QT_IM_MODULE,kime
env = XMODIFIERS,@im=kime
env = GTK_IM_MODULE,kime
env = SDL_IM_MODULE,kime

# GTK
env = GDK_SCALE,1
env = GDK_BACKEND,wayland


# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Disable appimage launcher by default
env = APPIMAGELAUNCHER_DISABLE,1

# OZONE
env = OZONE_PLATFORM,wayland

# Java
env = _JAVA_AWT_WM_NONREPARENTING,1
env = AWT_TOOLKIT,MToolkit
