group {
  insert_after_current = true
  focus_removed_window = true
  col.border_active = rgb(268bd2)
  col.border_inactive = rgb(6c7c80)
  col.border_locked_active = rgb(d33682)
  col.border_locked_inactive = rgb(b58900)
  drag_into_group = 2

  groupbar {
    enabled = true
    font_family = "JetBrainsMonoNL Nerd Font Mono 10"
    font_size =10 
    gradients = false 
    height = 50
    priority = 3
    render_titles = false
    scrolling = true
    text_color = rgb(fdf6e3)
    col.active = rgb(268bd2)
    col.inactive = rgb(6c7c80)
    col.locked_active = rgb(dc322f)
    col.locked_inactive = rgb(073642)
  }
}
