
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


windowrule = noinitialfocus,class:(jetbrains-)(.*), floating:1
#windowrulev2=noinitialfocus,class:(jetbrains-)(.*), floating:1
windowrulev2=center, class:(jetbrains-)(.*), title:^$, initialTitle:^$, floating:1
#windowrulev2=center, class:(jetbrains-)(.*), initialTitle:(.+), floating:1

# common modals
windowrule = float,title:^(Open)$
windowrule = float,title:^(Open File)$
windowrule = float,title:^(Open Files)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Confirm to replace files)$
windowrule = float,title:^(File Operation Progress)$


# windowrule v2 - float
windowrulev2 = float, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float, class:^(org.freedesktop.impl.portal.desktop.kde)$
windowrulev2 = float, class:([Zz]oom|onedriver|onedriver-launcher)$
windowrulev2 = float, class:([Tt]hunar), title:(File Operation Progress)
windowrulev2 = float, class:([Tt]hunar), title:(Confirm to replace files)
windowrulev2 = float, class:(xdg-desktop-portal-gtk)
windowrulev2 = float, class:^([Rr]ofi)$
windowrulev2 = float, class:^(eog)$
windowrulev2 = float, class:^(engrampa)$
windowrulev2 = float, class:^(obsidian)$
windowrulev2 = float, class:^(pavucontrol|org.pulseaudio.pavucontrol)$
windowrulev2 = float, class:^(nwg-look|nwg-displays|qt5ct|qt6ct|mpv)$
windowrulev2 = float, class:^(nm-applet|nm-connection-editor|blueman-manager)$
windowrulev2 = float, class:^(gnome-system-monitor|org.gnome.SystemMonitor)$ # system monitor
